package kr.co.lion.modigm.util

enum class Skill(val num: Int, val displayName: String) {
    PYTHON(1, "Python"),
    JAVA(2, "Java"),
    CSHARP(3, "C#"),
    JAVASCRIPT(4, "JavaScript"),
    RUBY(5, "Ruby"),
    GO(6, "Go"),
    SWIFT(7, "Swift"),
    KOTLIN(8, "Kotlin"),
    R(9, "R"),
    CPP(10, "C++"),
    PHP(11, "PHP"),
    RUST(12, "Rust"),
    TYPESCRIPT(13, "TypeScript"),
    HTML(14, "HTML"),
    CSS(15, "CSS"),
    REACT(16, "React"),
    ANGULAR(17, "Angular"),
    VUEJS(18, "Vue.js"),
    NPM(19, "NPM"),
    WEBPACK(20, "Webpack"),
    BABEL(21, "Babel"),
    NODEJS(22, "Node.js"),
    EXPRESS(23, "Express"),
    DJANGO(24, "Django"),
    FLASK(25, "Flask"),
    SPRING(26, "Spring"),
    MYSQL(27, "MySQL"),
    POSTGRESQL(28, "PostgreSQL"),
    MONGODB(29, "MongoDB"),
    REDIS(30, "Redis"),
    SWIFT_IOS(31, "Swift(iOS)"),
    REACT_NATIVE(32, "React Native"),
    FLUTTER(33, "Flutter"),
    PANDAS(34, "Pandas"),
    NUMPY(35, "NumPy"),
    SCIPY(36, "SciPy"),
    SCIKIT_LEARN(37, "scikit-learn"),
    TENSORFLOW(38, "TensorFlow"),
    PYTORCH(39, "PyTorch"),
    JUPYTER(40, "Jupyter Notebook"),
    DOCKER(41, "Docker"),
    KUBERNETES(42, "Kubernetes"),
    AWS(43, "AWS"),
    GOOGLE_CLOUD(44, "Google Cloud"),
    AZURE(45, "Azure"),
    UNITY(46, "Unity"),
    UNREAL_ENGINE(47, "Unreal Engine"),
    BLENDER(48, "Blender"),
    WIRESHARK(49, "Wireshark"),
    METASPLOIT(50, "Metasploit"),
    AUTHENTICATION(51, "인증"),
    NETWORK_SECURITY(52, "네트워크 보안"),
    KALI_LINUX(53, "Kali Linux"),
    SKETCH(54, "Sketch"),
    ADOBE_XD(55, "Adobe XD"),
    FIGMA(56, "Figma"),
    HADOOP(57, "Hadoop"),
    SPARK(58, "Spark"),
    HDFS(59, "HDFS"),
    CASSANDRA(60, "Cassandra"),
    KAFKA(61, "Apache Kafka"),
    FLINK(62, "Apache Flink"),
    OTHER(63, "기타"),
    TOTAL(64, "전체");

    companion object {
        fun fromNum(num: Int): Skill {
            return values().find { it.num == num } ?: OTHER
        }
    }
}